name: Node.js CI with SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.16.0" # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build # Adjust according to your build command

      - name: Run tests
        run: npm test # Adjust according to your test command

  sonar:
    runs-on: ubuntu-latest
    needs: build # Ensure this runs after the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Store your SonarQube token in GitHub Secrets
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} # Store your SonarQube URL in GitHub Secrets
        run: |
          npm install -g sonar-scanner
          sonar-scanner -X \
             -Dsonar.projectKey=Sonar_test_demo \
             -Dsonar.sources=. \
             -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
             -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
             -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
